### ISSUE TITLE
subscription fields

### ISSUE THREAD

**Issue by ahmettaha** [devdaves/AppleReceiptVerifier#3]
Can you please add fields to support auto-reneral subscriptions such as latest_receipt and latest_receipt_info.

Thanks.

**Comment by kYann** [comment]
See pull request https://github.com/devdaves/AppleReceiptVerifier/pull/4

**Comment by devdaves** [comment]
kYann, thanks for putting this together.  I will get this merged and update nuget tonight.

**Comment by devdaves** [comment]
Code merged in.  Updated package in nuget now.

**Comment by kYann** [comment]
Thanks !
